package com.example.sekmeszodynas

val THEMES_DATA = mapOf(
    "1" to Theme("1", "1. Глагол «быть» и основные слова", listOf(
        Word("быть", "būti, yra, buvo", "v"),
        Word("не быть", "nebūti, nėra, nebuvo", "v"),
        Word("да", "taip", "other"),
        Word("нет", "ne", "other"),
        Word("здесь", "čia", "adv"),
        Word("и", "ir", "other"),
        Word("и / а", "o", "other"),
        Word("преподаватель университета", "dėstytojas, dėstytoja", "n"),
        Word("студент, студентка", "studentas, studentė", "n"),
        Word("имя", "vardas", "n"),
        Word("фамилия", "pavardė", "n")
    )),
    "2" to Theme("2", "2. Общение", listOf(
        Word("говорить", "kalbėti, kalba, kalbėjo", "v"),
        Word("понимать", "suprasti, supranta, suprato", "v"),
        Word("но", "bet", "other"),
        Word("плохо", "blogai", "adv"),
        Word("хорошо", "gerai", "adv"),
        Word("так себе", "šiaip sau", "other"),
        Word("также, тоже", "taip pat", "adv"),
        Word("немного", "truputį", "adv"),
        Word("господин", "ponas", "n"),
        Word("госпожа", "ponia", "n"),
        Word("друг, подруга", "draugas, draugė", "n")
    )),
    "3" to Theme("3", "3. Город, места и учреждения", listOf(
        Word("жить", "gyventi, gyvena, gyveno", "v"),
        Word("работать", "dirbti, dirba, dirbo", "v"),
        Word("учиться, изучать", "studijuoti, studijuoja, studijavo", "v"),
        Word("коллега", "bendradarbis, bendradarbė", "n"),
        Word("сосед, соседка", "kaimynas, kaimynė", "n"),
        Word("столица", "sostinė", "n"),
        Word("город", "miestas", "n"),
        Word("центр", "centras", "n"),
        Word("старый город", "senamiestis, senamiesčio", "n"),
        Word("адрес", "adresas", "n"),
        Word("телефон (номер телефона)", "telefonas (telefono numeris)", "n"),
        Word("дом", "namas", "n"),
        Word("квартира", "butas", "n"),
        Word("комната", "kambarys", "n"),
        Word("общежитие", "bendrabutis, bendrabučio", "n"),
        Word("отель", "viešbutis, viešbučio", "n"),
        Word("церковь", "bažnyčia", "n"),
        Word("посольство", "ambasada", "n"),
        Word("банк", "bankas", "n"),
        Word("почта", "paštas", "n"),
        Word("министерство", "ministerija", "n"),
        Word("бюро, офис", "biuras", "n"),
        Word("университет", "universitetas", "n"),
        Word("школа", "mokykla", "n"),
        Word("детский сад", "vaikų darželis, darželio", "n"),
        Word("библиотека", "biblioteka", "n"),
        Word("книжный магазин", "knygynas", "n"),
        Word("ресторан", "restoranas", "n"),
        Word("бар", "baras", "n"),
        Word("кафе", "kavinė", "n"),
        Word("столовая", "valgykla", "n"),
        Word("торговый центр", "prekybos centras", "n"),
        Word("магазин", "parduotuvė", "n"),
        Word("киоск", "kioskas", "n"),
        Word("рынок", "turgus", "n"),
        Word("парикмахерская", "kirpykla", "n"),
        Word("салон красоты", "grožio salonas", "n"),
        Word("кинотеатр", "kino teatras", "n"),
        Word("театр", "teatras", "n"),
        Word("музей", "muziejus", "n"),
        Word("замок", "pilis, pilies", "n"),
        Word("спортивный клуб", "sporto klubas", "n"),
        Word("больница", "ligoninė", "n"),
        Word("клиника", "klinika", "n"),
        Word("аптека", "vaistinė", "n"),
        Word("улица", "gatvė", "n"),
        Word("аллея", "alėja", "n"),
        Word("проспект", "prospektas", "n"),
        Word("площадь", "aikštė", "n"),
        Word("аэропорт", "oro uostas", "n"),
        Word("станция", "stotis, stoties", "n"),
        Word("автобусная станция", "autobusų stotis", "n"),
        Word("железнодорожная станция", "geležinkelio stotis", "n"),
        Word("остановка (автобуса, троллейбуса, трамвая)", "stotelė", "n"),
        Word("работа", "darbas", "n"),
        Word("река", "upė", "n"),
        Word("мост", "tiltas", "n"),
        Word("озеро", "ežeras", "n"),
        Word("море", "jūra", "n"),
        Word("парк", "parkas", "n"),
        Word("лес", "miškas", "n"),
        Word("рядом", "arti", "adv"),
        Word("далеко", "toli", "adv"),
        Word("дома", "namie", "adv")
    )),
    "4" to Theme("4", "4. Время и дни недели", listOf(
        Word("неделя", "savaitė", "n"),
        Word("понедельник", "pirmadienis, pirmadienio", "n"),
        Word("вторник", "antradienis, -io", "n"),
        Word("среда", "trečiadienis, -io", "n"),
        Word("четверг", "ketvirtadienis, -io", "n"),
        Word("пятница", "penktadienis, -io", "n"),
        Word("суббота", "šeštadienis, -io", "n"),
        Word("воскресенье", "sekmadienis, -io", "n"),
        Word("выходные", "savaitgalis, savaitgalio", "n"),
        Word("час", "valanda", "n"),
        Word("половина", "pusė", "n"),
        Word("идти (пешком)", "eiti, eina, ėjo", "v"),
        Word("спешить, торопиться", "skubėti, skuba, skubėjo", "v"),
        Word("встречаться", "susitikti, susitinka, susitiko", "v"),
        Word("ехать (на транспорте)", "važiuoti, važiuoja, važiavo", "v"),
        Word("опаздывать", "vėluoti, vėluoja, vėlavo", "v"),
        Word("вместе", "kartu", "adv"),
        Word("утро", "rytas", "n"),
        Word("день", "diena", "n"),
        Word("вечер", "vakaras", "n"),
        Word("ночь", "naktis, nakties", "n"),
        Word("после обеда (PM)", "po pietų", "other"),
        Word("до обеда (AM)", "prieš pietus", "other")
    )),
    "5" to Theme("5", "5. Семья, родственники и домашние животные", listOf(
        Word("семья", "šeima", "n"),
        Word("родители", "tėvai", "n"),
        Word("отец, папа", "tėvas; tėtis, tėčio", "n"),
        Word("мать, мама", "motina, mama", "n"),
        Word("ребёнок", "vaikas", "n"),
        Word("дочь", "duktė", "n"),
        Word("сын", "sūnus", "n"),
        Word("жена", "žmona", "n"),
        Word("муж, мужчина", "vyras", "n"),
        Word("сестра", "sesuo", "n"),
        Word("брат", "brolis, brolio", "n"),
        Word("дедушка", "senelis, senelio", "n"),
        Word("бабушка", "senelė / močiutė", "n"),
        Word("внук, внучка", "anūkas, anūkė", "n"),
        Word("родственники", "giminės", "n"),
        Word("тётя", "teta", "n"),
        Word("дядя", "dėdė", "n"),
        Word("двоюродный брат", "pusbrolis, pusbrolio", "n"),
        Word("двоюродная сестра", "pusseserė", "n"),
        Word("племянница", "dukterėčia", "n"),
        Word("племянник", "sūnėnas", "n"),
        Word("женатый (мужчина)", "vedęs", "adj"),
        Word("замужняя (женщина)", "ištekėjusi", "adj"),
        Word("разведённый, разведённая", "išsiskyręs, išsiskyrusi", "adj"),
        Word("умерший, умершая", "miręs, mirusi", "adj"),
        Word("человек", "žmogus", "n"),
        Word("женщина", "moteris, moters", "n"),
        Word("молодой человек", "vaikinas", "n"),
        Word("девушка", "mergina", "n"),
        Word("мальчик", "berniukas", "n"),
        Word("девочка", "mergaitė", "n"),
        Word("школьник", "mokinys", "n"),
        Word("школьница", "mokinė", "n"),
        Word("домашнее животное", "naminis gyvūnas", "n"),
        Word("кошка", "katė", "n"),
        Word("собака", "šuo", "n"),
        Word("этот", "šis", "other"),
        Word("эти (м.р.)", "šie", "other"),
        Word("эта", "ši", "other"),
        Word("эти (ж.р.)", "šios", "other"),
        Word("музыка", "muzika", "n"),
        Word("литература", "literatūra", "n"),
        Word("спорт", "sportas", "n"),
        Word("театр", "teatras", "n"),
        Word("любить", "mylėti, myli, mylėjo ką?", "v"),
        Word("сидеть", "sėdėti, sėdi, sėdėjo", "v"),
        Word("стоять", "stovėti, stovi, stovėjo", "v"),
        Word("иметь", "turėti, turi, turėjo ką?", "v"),
        Word("смотреть, наблюдать", "žiūrėti, žiūri, žiūrėjo ką?", "v"),
        Word("нравиться", "mėgti, mėgsta, mėgo ką?", "v"),
        Word("заниматься спортом", "sportuoti, sportuoja, sportavo", "v"),
        Word("ходить", "vaikščioti, vaikščioja, vaikščiojo", "v")
    )),
    "6" to Theme("6", "6. Прилагательные и описания", listOf(
        Word("высокий / высокая", "aukštas, aukšta", "adj"),
        Word("дружелюбный / дружелюбная", "draugiškas, draugiška", "adj"),
        Word("добрый / добрая, хороший / хорошая", "geras, gera", "adj"),
        Word("молодой / молодая", "jaunas, jauna", "adj"),
        Word("весёлый / весёлая", "linksmas, linksma", "adj"),
        Word("грустный / грустная", "liūdnas, liūdna", "adj"),
        Word("маленький / маленькая", "mažas, maža", "adj"),
        Word("милый / милая", "mielas, miela", "adj"),
        Word("умный / умная", "protingas, protinga", "adj"),
        Word("старый / старая", "senas, sena", "adj"),
        Word("низкий / низкая", "žemas, žema", "adj"),
        Word("красивый / красивая", "gražus, graži", "adj"),
        Word("интересный / интересная", "įdomus, įdomi", "adj"),
        Word("приятный / приятная", "malonus, maloni", "adj"),
        Word("отличный / отличная", "puikus, puiki", "adj"),
        Word("светлый / светлая, блондин / блондинка", "šviesus, šviesi", "adj"),
        Word("тёмный / тёмная", "tamsus, tamsi", "adj"),
        Word("большой / большая", "didelis, didelė", "adj"),
        Word("средний / средняя", "vidurinis, vidurinė", "adj"),
        Word("младший / младшая", "jaunesnis, jaunesnė", "adj"),
        Word("самый младший / самая младшая", "jauniausias, jauniausia", "adj"),
        Word("старший / старшая", "vyresnis, vyresnė", "adj"),
        Word("самый старший / самая старшая", "vyriausias, vyriausia", "adj"),
        Word("тот", "tas", "other"),
        Word("та", "ta", "other"),
        Word("те (м.р.)", "tie", "other"),
        Word("те (ж.р.)", "tos", "other")
    )),
    "7" to Theme("7", "7. Еда и напитки", listOf(
        Word("молочные продукты", "pieno produktai", "n"),
        Word("молоко", "pienas", "n"),
        Word("сметана", "grietinė", "n"),
        Word("йогурт", "jogurtas", "n"),
        Word("кефир", "kefyras", "n"),
        Word("сыр", "sūris, sūrio", "n"),
        Word("масло", "sviestas", "n"),
        Word("творог", "varškė", "n"),
        Word("хлеб", "duona", "n"),
        Word("чёрный хлеб", "juoda duona", "n"),
        Word("свежий хлеб", "šviesi duona", "n"),
        Word("батон", "batonas", "n"),
        Word("мясо", "mėsa", "n"),
        Word("говядина", "jautiena", "n"),
        Word("индейка", "kalakutiena", "n"),
        Word("свинина", "kiauliena", "n"),
        Word("курятина", "vištiena", "n"),
        Word("колбаса", "dešra", "n"),
        Word("сосиски", "dešrelės", "n"),
        Word("ветчина", "kumpis, kumpio", "n"),
        Word("рыба", "žuvis, žuvies", "n"),
        Word("напитки", "gėrimai", "n"),
        Word("вода", "vanduo, vandens", "n"),
        Word("сок", "sultys, sulčių", "n"),
        Word("чай", "arbata", "n"),
        Word("кофе", "kava", "n"),
        Word("квас", "gira", "n"),
        Word("сладости", "saldumynai", "n"),
        Word("булочка", "bandelė", "n"),
        Word("мёд", "medus", "n"),
        Word("пирог", "pyragas", "n"),
        Word("шоколад", "šokoladas", "n"),
        Word("пончик", "spurga", "n"),
        Word("торт", "tortas", "n"),
        Word("каша, пюре", "košė", "n"),
        Word("яйцо", "kiaušinis, kiaušinio", "n"),
        Word("бутерброд", "sumuštinis, sumuštinio", "n"),
        Word("завтрак", "pusryčiai", "n"),
        Word("обед", "pietūs", "n"),
        Word("ужин", "vakarienė", "n"),
        Word("голодный / голодная", "alkanas, alkana", "adj"),
        Word("сытый / сытая", "sotus, soti", "adj"),
        Word("вкусный / вкусная", "skanus, skani", "adj"),
        Word("тёплый / тёплая", "šiltas, šilta", "adj"),
        Word("холодный / холодная", "šaltas, šalta", "adj"),
        Word("горячий / горячая", "karštas, karšta", "adj"),
        Word("жареный / печёный / запечённый / на гриле", "keptas, kepta", "adj"),
        Word("варёный / приготовленный", "virtas, virta", "adj"),
        Word("чёрный / чёрная", "juodas, juoda", "adj"),
        Word("нравиться", "patikti, patinka, patiko kam? kas?", "v"),
        Word("любить", "mėgti, mėgsta, mėgo ką?", "v"),
        Word("хотеть", "norėti, nori, norėjo ko?", "v"),
        Word("есть", "valgyti, valgo, valgė ką?, ko?", "v"),
        Word("пить", "gerti, geria, gėrė ką?", "v"),
        Word("пробовать", "ragauti, ragauja, ragavo ką?, ko?", "v"),
        Word("брать", "imti, ima, ėmė ką?, ko?", "v"),
        Word("передавать", "paduoti, paduoda, padavė ką?, ko?", "v"),
        Word("класть", "įdėti, įdeda, įdėjo ką?, ko?", "v"),
        Word("наливать", "įpilti, įpila, įpylė ko?", "v"),
        Word("завтракать", "pusryčiauti, pusryčiauja, pusryčiavo", "v"),
        Word("обедать", "pietauti, pietauja, pietavo", "v"),
        Word("ужинать", "vakarieniauti, vakarieniauja, vakarieniavo", "v")
    )),
    "8" to Theme("8", "8. Рынок и продукты", listOf(
        Word("рынок", "turgus", "n"), Word("продавец / продавщица", "pardavėjas, pardavėja", "n"),
        Word("кусочек / кусок", "gabaliukas; gabalėlis, gabalėlio", "n"), Word("килограмм", "kilogramas", "n"),
        Word("пакет", "maišelis, maišelio", "n"), Word("цена", "kaina", "n"),
        Word("евро", "euras", "n"), Word("цент", "centas", "n"),
        Word("овощи", "daržovės", "n"), Word("огурец", "agurkas", "n"),
        Word("баклажан", "baklažanas", "n"), Word("свёкла", "burokėlis, burokėlio", "n"),
        Word("картофель", "bulvė", "n"), Word("кабачок", "cukinija", "n"),
        Word("чеснок", "česnakas", "n"), Word("капуста", "kopūstas", "n"),
        Word("тыква", "moliūgas", "n"), Word("морковь", "morka", "n"),
        Word("помидор", "pomidoras", "n"), Word("фасоль", "pupelės", "n"),
        Word("лук", "svogūnas", "n"), Word("горох", "žirniai", "n"),
        Word("фрукты", "vaisiai", "n"), Word("апельсин", "apelsinas", "n"),
        Word("банан", "bananas", "n"), Word("лимон", "citrina", "n"),
        Word("груша", "kriaušė", "n"), Word("яблоко", "obuolys", "n"),
        Word("ягоды", "uogos", "n"), Word("малина", "avietės", "n"),
        Word("клубника", "braškės", "n"), Word("смородина", "serbentai", "n"),
        Word("виноград", "vynuogės", "n"), Word("вишня", "vyšnios", "n"),
        Word("орехи", "riešutai", "n"), Word("приправы", "prieskoniai", "n"),
        Word("базилик", "bazilikai", "n"), Word("тмин", "kmynai", "n"),
        Word("укроп", "krapai", "n"), Word("лавровый лист", "lauro lapai", "n"),
        Word("мята", "mėtos", "n"), Word("петрушка", "petražolės", "n"),
        Word("перец", "pipirai", "n"), Word("орегано", "raudonėliai", "n"),
        Word("суп", "sriuba", "n"), Word("салат", "salotos", "n"),
        Word("белый / белая", "baltas, balta", "adj"), Word("жёлтый / жёлтая", "geltonas, geltona", "adj"),
        Word("синий / синяя", "mėlynas, mėlyna", "adj"), Word("красный / красная", "raudonas, raudona", "adj"),
        Word("зелёный, сырой / зелёная, сырая", "žalias, žalia", "adj"),
        Word("делать, производить", "daryti, daro, darė ką?", "v"), Word("жарить, печь, запекать", "kepti, kepa, kepė ką?", "v"),
        Word("варить, кипятить", "virti, verda, virė ką?", "v"), Word("давать", "duoti, duoda, davė ką?, ko?", "v"),
        Word("покупать", "pirkti, perka, pirko ką?, ko?", "v"),
        Word("сладкий / сладкая", "saldus, saldi", "adj"), Word("кислый / кислая", "rūgštus, rūgšti", "adj"),
        Word("свежий / свежая", "šviežias, šviežia", "adj"), Word("несвежий / несвежая", "senas, sena", "adj"),
        Word("жирный / насыщенный", "riebus, riebi", "adj"), Word("копчёный / копчёная", "rūkytas, rūkyta", "adj")
    )),
    "9" to Theme("9", "9. Заведения, меню, блюда и напитки", listOf(
        Word("кафе", "kavinė", "n"), Word("пекарня", "kepyklėlė", "n"),
        Word("ресторан", "restoranas", "n"), Word("бар", "baras", "n"),
        Word("пиццерия", "picerija", "n"), Word("официант / официантка", "padavėjas, padavėja", "n"),
        Word("меню", "meniu", "n"), Word("обед дня", "dienos pietūs", "n"),
        Word("стол", "staliukas", "n"), Word("счёт", "sąskaita", "n"),
        Word("обычно", "paprastai", "adv"), Word("блюдо", "patiekalas", "n"),
        Word("суп дня", "dienos sriuba", "n"), Word("овощной суп", "daržovių sriuba", "n"),
        Word("грибной суп", "grybų sriuba", "n"), Word("свекольный суп", "burokėlių sriuba", "n"),
        Word("овощной салат", "daržovių salotos", "n"), Word("томатный салат", "pomidorų salotos", "n"),
        Word("капустный салат", "kopūstų salotos", "n"), Word("литовский салат", "lietuviškos salotos", "n"),
        Word("омлет", "omletas", "n"), Word("яичница", "kiaušinienė", "n"),
        Word("яичница с беконом", "kiaušinienė su šonine", "n"),
        Word("сэндвич", "sumuštinis, sumuštinio", "n"), Word("сэндвич с ветчиной и салатом", "sumuštinis su kumpiu ir salotomis", "n"),
        Word("жаркое / гриль", "kepsnys", "n"), Word("куриное жаркое", "vištienos kepsnys", "n"),
        Word("свиное жаркое", "kiaulienos kepsnys", "n"), Word("говяжье жаркое", "jautienos kepsnys", "n"),
        Word("пицца", "pica", "n"), Word("блины", "blynai", "n"),
        Word("картофельные блины", "bulvių blynai", "n"), Word("блинчик", "blynelis, blynelio", "n"),
        Word("блинчики с сыром", "blyneliai su sūriu", "n"), Word("блинчики с яблоками", "blyneliai su obuoliais", "n"),
        Word("блинчики с вареньем", "blyneliai su uogiene", "n"),
        Word("макароны", "makaronai", "n"), Word("макароны с сыром", "makaronai su sūriu", "n"),
        Word("рис", "ryžiai", "n"), Word("рис с овощами", "ryžiai su daržovėmis", "n"),
        Word("каша, пюре", "košė", "n"), Word("овсяная каша", "avižinė košė", "n"),
        Word("гречневая каша", "grikių košė", "n"),
        Word("десерт", "desertas", "n"), Word("мороженое", "ledai", "n"),
        Word("пирожное", "pyragaitis, pyragaičio", "n"), Word("торт", "tortas", "n"),
        Word("напиток", "gėrimas", "n"), Word("газированная вода", "gazuotas vanduo", "n"),
        Word("негазированная вода", "negazuotas vanduo", "n"), Word("чай", "arbata", "n"),
        Word("чёрный чай", "juoda arbata", "n"), Word("зелёный чай", "žalia arbata", "n"),
        Word("фруктовый чай", "vaisinė arbata", "n"), Word("травяной чай", "žolelių arbata", "n"),
        Word("мятный чай", "mėtų arbata", "n"), Word("коктейль", "kokteilis, kokteilio", "n"),
        Word("сок", "sultys", "n"), Word("яблочный сок", "obuolių sultys", "n"),
        Word("апельсиновый сок", "apelsinų sultys", "n"), Word("ананасовый сок", "ananasų sultys", "n"),
        Word("виноградный сок", "vynuogių sultys", "n"), Word("морковный сок", "morkų sultys", "n"),
        Word("томатный сок", "pomidorų sultys", "n"),
        Word("сахар", "cukrus", "n"), Word("соль", "druska", "n"),
        Word("горчица", "garstyčios", "n"), Word("хрен", "krienai", "n"),
        Word("майонез", "majonezas", "n"), Word("соус", "padažas", "n"),
        Word("варенье", "uogienė", "n"), Word("уксус", "actas", "n"),
        Word("масло (растительное)", "aliejus", "n"),
        Word("литовские блюда", "lietuviški patiekalai", "n"), Word("холодный свекольник", "šaltibarščiai", "n"),
        Word("цеппелины", "cepelinai", "n"), Word("медовый торт", "medaus tortas", "n"),
        Word("шакотис", "šakotis, šakočio", "n"), Word("квас", "gira", "n"),
        Word("острый / острая", "aštrus, aštri", "adj"), Word("мягкий / нежный", "švelnus, švelni", "adj"),
        Word("солёный / солёная", "sūrus, sūri", "adj")
    )),
    "10" to Theme("10", "10. Транспорт", listOf(
        Word("транспортные средства", "transporto priemonės", "n"), Word("автомобиль", "automobilis, automobilio", "n"),
        Word("парковка", "automobilių stovėjimo aikštelė", "n"), Word("велосипед", "dviratis, dviračio", "n"),
        Word("самокат", "paspirtukas", "n"), Word("автобус", "autobusas", "n"),
        Word("автобусная станция", "autobuso stotis, stoties", "n"), Word("платформа (автобус)", "autobuso platforma", "n"),
        Word("поезд", "traukinys", "n"), Word("скоростной поезд", "greitasis traukinys", "n"),
        Word("железнодорожный вокзал", "geležinkelio stotis, stoties", "n"), Word("платформа (поезд)", "peronas", "n"),
        Word("путь, колея", "kelias", "n"), Word("самолёт", "lėktuvas", "n"),
        Word("аэропорт", "oro uostas", "n"), Word("общественный транспорт", "viešasis transportas", "n"),
        Word("скоростной автобус", "greitasis autobusas", "n"), Word("ночной автобус", "naktinis autobusas", "n"),
        Word("троллейбус", "troleibusas", "n"), Word("остановка автобуса / троллейбуса", "autobusų, troleibusų stotelė", "n"),
        Word("информация", "informacija", "n"), Word("расписание", "tvarkaraštis, tvarkaraščio", "n"),
        Word("билет", "autobuso, troleibuso, traukinio bilietas", "n"), Word("электронный билет", "elektroninis bilietas", "n"),
        Word("билет со скидкой", "bilietas su nuolaida", "n"), Word("билет туда-обратно", "bilietas pirmyn ir atgal", "n"),
        Word("билет в одну сторону", "bilietas į vieną pusę", "n"), Word("билетная касса", "bilietų kasa", "n"),
        Word("пункты проката", "nuomos punktas", "n"), Word("получение / возврат", "paėmimas, grąžinimas", "n"),
        Word("бронь", "rezervacija", "n"), Word("заправочная станция", "degalinė", "n"),
        Word("топливо", "degalai / kuras", "n"), Word("бензин", "benzinas", "n"),
        Word("дизель", "dyzelinas", "n"), Word("газ", "dujos", "n"),
        Word("топливная колонка", "kolonėlė", "n"), Word("воздух", "oras", "n"),
        Word("вода", "vanduo", "n"), Word("быстрый", "greitas, greita", "adj"),
        Word("медленный", "lėtas, lėta", "adj"), Word("дешёвый", "pigus, pigi", "adj"),
        Word("дорогой", "brangus, brangi", "adj"), Word("удобный", "patogus, patogi", "adj"),
        Word("долгосрочный / краткосрочный", "ilgalaikė, trumpalaikė", "adj"),
        Word("справа", "dešinėje", "adv"), Word("слева", "kairėje", "adv"),
        Word("направо", "į dešinę", "adv"), Word("налево", "į kairę", "adv"),
        Word("прямо", "tiesiai", "adv"), Word("затем", "paskui", "adv"),
        Word("дойти пешком", "nuėti, nueina, nuėjo", "v"), Word("доехать", "nuvažiuoti, nuvažiuoja, nuvažiavo", "v"),
        Word("приезжать", "atvažiuoti, atvažiuoja, atvažiavo", "v"), Word("уезжать", "išvažiuoti, išvažiuoja, išvažiavo", "v"),
        Word("поворачивать", "pasukti, pasuka, pasuko", "v"), Word("садиться", "lipti, lipa, lipo", "v"),
        Word("выходить", "išlipti, išlipa, išlipo", "v"), Word("лететь", "skristi, skrenda, skrido", "v"),
        Word("нужно, требуется", "reikėti, reikia, reikėjo", "v"), Word("доливать, пополнять", "papildyti, papildo, papildė", "v"),
        Word("как", "kaip", "other")
    )),
    "11" to Theme("11", "11. Путешествия и автомобиль", listOf(
        Word("путешествие, поездка", "kelionė", "n"), Word("пассажир", "keleivis, keleivė", "n"),
        Word("водитель", "vairuotojas, vairuotoja", "n"), Word("водительские права", "vairuotojo pažymėjimas", "n"),
        Word("страховка автомобиля", "automobilio draudimas", "n"), Word("плата, сбор", "mokestis", "n"),
        Word("месяц", "mėnuo, mėnesio", "n"), Word("дата", "data", "n"),
        Word("сутки", "para", "n"), Word("запчасти автомобиля", "automobilio dalys", "n"),
        Word("салон автомобиля", "salonas", "n"), Word("руль", "vairas", "n"),
        Word("ключи", "raktai", "n"), Word("тормоза", "stabdžiai", "n"),
        Word("шины", "padangos", "n"), Word("дворники", "valytuvai", "n"),
        Word("смазочные материалы", "tepalai", "n"), Word("автомойка", "automobilio plovykla", "n"),
        Word("чистка салона", "salono valymas", "n"), Word("мойка автомобиля", "automobilio plovimas", "n"),
        Word("автосервис / ремонт", "autoservisas / automobilio taisykla", "n"), Word("техпомощь на дороге", "techninė pagalba kelyje", "n"),
        Word("скорость", "greitis, greičio", "n"), Word("разрешено", "galima", "adj"),
        Word("запрещено", "draudžiama", "adj"), Word("новый", "naujas, nauja", "adj"),
        Word("старый", "senas, sena", "adj"), Word("чистый", "švarus, švari", "adj"),
        Word("грязный", "nešvarus, nešvari", "adj"), Word("длинный", "ilgas, ilga", "adj"),
        Word("короткий", "trumpas, trumpa", "adj"), Word("занятый", "užimtas, užimta", "adj"),
        Word("свободный", "laisvas, laisva", "adj"), Word("следующий", "kitas, kita", "adj"),
        Word("бесплатно", "nemokamas, nemokama", "adj"), Word("превышать скорость", "viršyti greitį", "v"),
        Word("путешествовать", "keliauti, keliauja, keliavo", "v"), Word("водить (машину)", "vairuoti, vairuoja, vairavo", "v"),
        Word("ехать", "važiuoti, važiuoja, važiavo", "v"), Word("резервировать", "rezervuoti, rezervuoja, rezervavo", "v"),
        Word("заказывать", "užsakyti, užsako, užsakė", "v"), Word("показывать", "parodyti, parodo, parodė", "v"),
        Word("останавливаться", "sustoti, sustoja, sustojo", "v"), Word("работать", "veikti, veikia, veikė", "v"),
        Word("ломаться", "sugesti, sugenda, sugedo", "v"), Word("чинить, ремонтировать", "pataisyti, pataiso, pataisė", "v"),
        Word("ремонтировать", "suremontuoti, suremontuoja, suremontavo", "v"), Word("мыть", "nuplauti, nuplauna, nuplovė", "v"),
        Word("чистить", "išvalyti, išvalo, išvalė", "v"), Word("заправляться", "pildyti, pila, pylė", "v"),
        Word("быстро", "greitai", "adv"), Word("кроме", "išskyrus ką?", "other")
    )),
    "12" to Theme("12", "12. Дом и мебель", listOf(
        Word("дом", "namas", "n"), Word("дом (как место)", "namai", "n"),
        Word("квартира", "butas", "n"), Word("лестничная площадка", "laiptinė", "n"),
        Word("лестница", "laiptai", "n"), Word("этаж", "aukštas", "n"),
        Word("лифт", "liftas", "n"), Word("балкон", "balkonas", "n"),
        Word("гараж", "garažas", "n"), Word("двор", "kiemas", "n"),
        Word("ворота", "vartai", "n"), Word("дверь", "durys, durų", "n"),
        Word("код двери", "durų kodas", "n"), Word("ключ", "raktas", "n"),
        Word("окно", "langas", "n"), Word("стена", "siena", "n"),
        Word("потолок", "lubos, lubų", "n"), Word("пол", "grindys, grindų", "n"),
        Word("ковёр", "kilimas", "n"), Word("комната", "kambarys, kambariai", "n"),
        Word("кухня", "virtuvė", "n"), Word("гостиная", "svetainė", "n"),
        Word("коридор", "koridorius", "n"), Word("ванная комната", "vonia", "n"),
        Word("душ", "dušas", "n"), Word("туалет", "tualetas", "n"),
        Word("спальня", "miegamasis, miegamieji", "n"), Word("подвал", "rūsys", "n"),
        Word("мебель", "baldai", "n"), Word("стол", "stalas", "n"),
        Word("стул", "kėdė", "n"), Word("кровать", "lova", "n"),
        Word("диван", "sofa", "n"), Word("кресло", "fotelis, fotelio", "n"),
        Word("шкаф", "spinta", "n"), Word("полка", "lentyna", "n"),
        Word("плата за теплоснабжение...", "mokesčiai už šildymą...", "n"), Word("уютный", "jaukus, jauki", "adj"),
        Word("спокойный, тихий", "ramus, rami", "adj"), Word("шумный", "triukšmingas, triukšminga", "adj"),
        Word("мягкий", "minkštas, minkšta", "adj"), Word("удобный", "patogus, patogi", "adj"),
        Word("оплачивать", "sumokėti, sumoka, sumokėjo", "v"), Word("закрывать", "uždaryti, uždaro, uždarė", "v"),
        Word("открывать", "atidaryti, atidaro, atidarė", "v"), Word("запирать", "užrakinti, užrakina, užrakino", "v"),
        Word("отпирать", "atrakinti, atrakina, atrakino", "v"), Word("сдавать в аренду", "nuomoti, nuomoja, nuomojo", "v"),
        Word("снимать", "išsinuomoti, išsinuomoja, išsinuomojo", "v"), Word("нужно, требуется", "reikėti, reikia, reikėjo", "v"),
        Word("искать", "ieškoti, ieško, ieškojo", "v"), Word("сидеть", "sėdėti, sėdi, sėdėjo", "v"),
        Word("лежать", "gulėti, guli, gulėjo", "v"), Word("спать", "miegoti, miega, miegojo", "v"),
        Word("на", "ant", "other")
    )),
    "13" to Theme("13", "13. Бытовая техника и уборка", listOf(
        Word("бытовая техника", "buitinė technika", "n"), Word("холодильник", "šaldytuvas", "n"),
        Word("духовка", "orkaitė", "n"), Word("плита", "viryklė", "n"),
        Word("микроволновая печь", "mikrobangų krosnelė", "n"), Word("посудомоечная машина", "indaplovė", "n"),
        Word("стиральная машина", "skalbyklė", "n"), Word("сушильная машина", "džiovyklė", "n"),
        Word("чайник", "virdulys", "n"), Word("кофеварка", "kavos aparatas", "n"),
        Word("пылесос", "dulkių siurblys", "n"), Word("утюг", "lygintuvas", "n"),
        Word("вещи, предметы", "daiktai", "n"), Word("телевизор", "televizorius", "n"),
        Word("лампа", "lempa", "n"), Word("зеркало", "veidrodis, veidrodžio", "n"),
        Word("картина", "paveikslas", "n"), Word("цветок", "gėlė", "n"),
        Word("ковёр, коврик", "kilimas", "n"), Word("посуда", "indai", "n"),
        Word("мусорное ведро", "šiukšlių dėžė", "n"), Word("мусор", "šiukšlės", "n"),
        Word("пыль", "dulkės", "n"), Word("грязь", "purvas", "n"),
        Word("уборка", "valymas", "n"), Word("уборщик / уборщица", "namų tvarkytojas, namų tvarkytoja", "n"),
        Word("свет", "šviesa", "n"), Word("труба", "vamzdis, vamzdžio", "n"),
        Word("кран", "čiaupas", "n"), Word("аварийная служба", "avarinė tarnyba", "n"),
        Word("ремонт", "remontas", "n"), Word("мастер", "meistras, meistrė", "n"),
        Word("сантехник", "santechnikas, santechnikė", "n"), Word("сосед", "kaimynas, kaimynė", "n"),
        Word("квадратный метр", "kvadratinis metras, m²", "n"), Word("квадратные метры", "kvadratiniai metrai", "n"),
        Word("чистый", "švarus, švari", "adj"), Word("грязный", "nešvarus, nešvari", "adj"),
        Word("аккуратный", "tvarkingas, tvarkinga", "adj"),
        Word("убирать", "tvarkyti, tvarko, tvarkė", "v"), Word("убирать (полностью)", "sutvarkyti, sutvarko, sutvarkė", "v"),
        Word("чистить, вытирать", "valyti, valo, valė", "v"), Word("вытирать", "nuvalyti, nuvalo, nuvalė", "v"),
        Word("убирать (мусор)", "išvalyti, išvalo, išvalė", "v"), Word("мыть посуду", "išplauti, išplauna, išplovė", "v"),
        Word("пылесосить", "išsiurbti, išsiurbia, išsiurbė", "v"), Word("выносить", "išnešti, išneša, išnešė", "v"),
        Word("включать", "įjungti, įjungia, įjungė", "v"), Word("выключать", "išjungti, išjungia, išjungė", "v"),
        Word("работать", "veikti, veikia, veikė", "v"), Word("ломаться", "sugesti, sugenda, sugedo", "v"),
        Word("чинить", "pataisyti, pataiso, pataisė", "v"), Word("от, с", "nuo", "other"),
        Word("под", "po", "other")
    )),
    "14" to Theme("14", "14. Одежда и аксессуары", listOf(
        Word("одежда", "drabužiai / rūbai", "n"), Word("свитер, джемпер", "megztinis, megztinio", "n"),
        Word("брюки", "kelnės", "n"), Word("юбка", "sijonas", "n"),
        Word("платье", "suknelė", "n"), Word("блузка", "palaidinė", "n"),
        Word("рубашка", "marškiniai", "n"), Word("пиджак, жакет", "švarkas", "n"),
        Word("костюм", "kostiumas", "n"), Word("футболка", "marškinėliai", "n"),
        Word("шорты", "šortai", "n"), Word("джинсы", "džinsai", "n"),
        Word("куртка", "striukė", "n"), Word("пальто", "paltas", "n"),
        Word("носки", "kojinės", "n"), Word("перчатки", "pirštinės", "n"),
        Word("шапка, кепка", "kepurė", "n"), Word("шарф", "šalikas", "n"),
        Word("нижнее бельё", "apatiniai drabužiai", "n"), Word("купальник", "maudymosi kostiumėlis", "n"),
        Word("плавки", "glaudės", "n"), Word("джемпер", "džemperis, džemperio", "n"),
        Word("жилет", "liemenė", "n"), Word("обувь", "avalynė", "n"),
        Word("туфли, ботинки", "batai", "n"), Word("туфли (лодочки)", "bateliai", "n"),
        Word("кроссовки", "sportbačiai", "n"), Word("сандалии", "basutės", "n"),
        Word("размер", "dydis, dydžio", "n"), Word("примерочная", "matavimosi kabina", "n"),
        Word("чек, квитанция", "kvitas", "n"), Word("распродажа", "išpardavimas", "n"),
        Word("скидка", "nuolaida", "n"), Word("шерстяной", "vilnonis, vilnonė", "adj"),
        Word("хлопковый", "medvilninis, medvilninė", "adj"), Word("кожаный", "odinis, odinė", "adj"),
        Word("синтетический", "sintetinis, sintetinė", "adj"), Word("светлый", "šviesus, šviesi", "adj"),
        Word("тёмный", "tamsus, tamsi", "adj"), Word("разноцветный", "margas, marga", "adj"),
        Word("однотонный", "vienspalvis, vienspalvė", "adj"), Word("розовый", "rausvas, rausva", "adj"),
        Word("голубой (светлый)", "žydras, žydra", "adj"), Word("оранжевый", "oranžinis, oranžinė", "adj"),
        Word("фиолетовый", "violetinis, violetinė", "adj"), Word("коричневый", "rudas, ruda", "adj"),
        Word("мужская одежда", "vyriškas, vyriška", "adj"), Word("женская одежда", "moteriškas, moteriška", "adj"),
        Word("детская одежда", "vaikiškas, vaikiška", "adj"), Word("зимний", "žieminis, žieminė", "adj"),
        Word("летний", "vasarinis, vasarinė", "adj"), Word("носить (одежду)", "dėvėti, dėvi, dėvėjo", "v"),
        Word("одеваться", "apsirengti, apsirenčia, apsirengė", "v"), Word("раздеваться", "nusirengti, nusirengia, nusirengė", "v"),
        Word("обувать", "apsiauti, apsiauna, apsiavė", "v"), Word("разувать", "nusiauti, nusiauna, nusiavė", "v"),
        Word("стоить", "kainuoti, kainuoja, kainavo", "v"), Word("показать", "parodyti, parodo, parodė", "v"),
        Word("примерить", "pasimatuoti, pasimatoja, pasimatavo", "v"), Word("купить", "nusipirkti, nusipirka, nusipirko", "v"),
        Word("подходить", "tikti, tinka, tiko", "v"), Word("делать покупки", "apsipirkti, apsiperka, apsipirko", "v"),
        Word("этот / эта", "šis, ši", "other"), Word("тот / та", "tas, ta", "other")
    )),
    "15" to Theme("15", "15. Аксессуары и услуги ателье", listOf(
        Word("кошелёк", "piniginė", "n"), Word("сумка (дамская)", "rankinė", "n"),
        Word("рюкзак", "kuprinė", "n"), Word("зонт", "skėtis, skėčio", "n"),
        Word("ремень", "diržas", "n"), Word("часы", "laikrodis, laikrodžio", "n"),
        Word("очки", "akiniai", "n"), Word("очки от солнца", "akiniai nuo saulės", "n"),
        Word("серьги", "auskarai", "n"), Word("кольцо", "žiedas", "n"),
        Word("цепочка", "grandinėlė", "n"), Word("расчёска", "šukos", "n"),
        Word("пуговица", "saga", "n"), Word("молния (застёжка)", "užtrauktukas", "n"),
        Word("карман", "kišenė", "n"), Word("рукав", "rankovė", "n"),
        Word("сантиметр (см)", "centimetras (cm)", "n"), Word("постельное бельё", "patalynė", "n"),
        Word("химчистка", "valykla", "n"), Word("химическая чистка одежды", "cheminis drabužių valymas", "n"),
        Word("прачечная", "skalbykla", "n"), Word("прачечная самообслуживания", "savitarnos skalbykla", "n"),
        Word("пятно", "dėmė", "n"), Word("ателье по пошиву", "siuvykla", "n"),
        Word("ремонтная мастерская", "taisykla", "n"), Word("портной / портниха", "siuvėjas, siuvėja", "n"),
        Word("длинный / длинная", "ilgas, ilga", "adj"),
        Word("короткий / короткая", "trumpas, trumpa", "adj"), Word("широкий / широкая", "platus, plati", "adj"),
        Word("узкий / узкая", "siauras, siaura", "adj"), Word("модный / модная", "madingas, madinga", "adj"),
        Word("старомодный / старомодная", "senamadiškas, senamadiška", "adj"), Word("золотой / золотая", "auksinis, auksinė", "adj"),
        Word("серебряный / серебряная", "sidabrinis, sidabrinė", "adj"), Word("деревянный / деревянная", "medinis, medinė", "adj"),
        Word("слишком короткий, маленький, …", "per trumpas, mažas, …", "other"), Word("носить", "nešioti, nešioja, nešiojo ką?", "v"),
        Word("подрубить", "palenkti, palenkia, palenkė ką?", "v"), Word("укоротить", "patrumpinti, patrumpina, patrumpino ką?", "v"),
        Word("починить", "pataisyti, pataiso, pataisė ką?", "v"), Word("сшить (заказать пошив)", "pasiūti, pasiūva, pasiūvo ką?", "v"),
        Word("пришить", "siūti, siuva, siuvo ką?", "v"), Word("забрать (получить)", "atsiimti, atsiima, atsiėmė ką?", "v"),
        Word("поменять", "pakeisti, pakeičia, pakeitė ką?", "v"), Word("вернуть", "grąžinti, grąžina, grąžino ką?", "v"),
        Word("почистить", "išvalyti, išvalo, išvalė ką?", "v"), Word("стирать", "skalbti, skalbia, skalbė ką?", "v")
    )),
    "16" to Theme("16", "16. Месяцы, части тела и здоровье", listOf(
        Word("месяцы", "mėnesiai", "n"), Word("январь", "sausis, sausio", "n"),
        Word("февраль", "vasaris, vasario", "n"), Word("март", "kovas", "n"),
        Word("апрель", "balandis, balandžio", "n"), Word("май", "gegužė", "n"),
        Word("июнь", "birželis, birželio", "n"), Word("июль", "liepa", "n"),
        Word("август", "rugpjūtis, rugpjūčio", "n"), Word("сентябрь", "rugsėjis, rugsėjo", "n"),
        Word("октябрь", "spalis, spalio", "n"), Word("ноябрь", "lapkritis, lapkričio", "n"),
        Word("декабрь", "gruodis, gruodžio", "n"), Word("тело", "kūnas", "n"),
        Word("голова", "galva", "n"), Word("лицо", "veidas", "n"),
        Word("глаз", "akis, akies", "n"), Word("ухо", "ausis, ausies", "n"),
        Word("нос", "nosis, nosies", "n"), Word("зуб", "dantis, danties", "n"),
        Word("горло", "gerklė", "n"), Word("рука", "ranka", "n"),
        Word("палец", "pirštas", "n"), Word("нога", "koja", "n"),
        Word("желудок", "skrandis, skrandžio", "n"), Word("живот", "pilvas", "n"),
        Word("спина", "nugara", "n"), Word("сердце", "širdis, širdies", "n"),
        Word("чувствовать себя", "jaustis, jaučiasi, jautėsi", "v"), Word("болеть (о боли)", "skaudėti, skauda, skaudėjo ką?", "v"),
        Word("температура", "temperatūra", "n"), Word("высокая, низкая, нормальная", "aukšta, žema, normali", "adj"),
        Word("иметь температуру / температурить", "turėti, turi, turėjo temperatūros / karščiuoti, karščiuoja, karščiavo", "v"),
        Word("болеть", "sirgti, serga, sirgo", "v"), Word("простудиться", "peršalti, peršąla, peršalo", "v"),
        Word("выздоравливать, поправляться", "(pa)sveikti, sveiksta, sveiko", "v"), Word("записаться (к врачу)", "užsiregistruoti, užsiregistruoja, užsiregistravo (pas gydytoją)", "v"),
        Word("здоровье", "sveikata", "n"), Word("здоровый / здоровая", "sveikas, sveika", "adj"),
        Word("усталый / усталая", "pavargęs, pavargusi", "adj"), Word("врач", "gydytojas, gydytoja", "n"),
        Word("врач общей практики, семейный врач", "šeimos gydytojas, šeimos gydytoja", "n"),
        Word("стоматолог", "odontologas, odontologė", "n"), Word("медсестра / медбрат", "slaugytojas, slaugytoja", "n"),
        Word("ветеринар", "veterinaras, veterinarė", "n"), Word("поликлиника", "poliklinika", "n"),
        Word("кабинет (врачебный)", "kabinetas", "n"), Word("больница", "ligoninė", "n"),
        Word("палата", "palata", "n"), Word("ветеринарная клиника", "veterinarijos klinika", "n"),
        Word("лежать в больнице", "gulėti, guli, gulėjo ligoninėje", "v"), Word("пациент / пациентка", "ligonis, ligonio ; ligonė", "n"),
        Word("возраст", "amžius", "n"), Word("год", "metai", "n"),
        Word("сто", "šimtas", "n"), Word("тысяча", "tūkstantis, tūkstančio", "n"),
        Word("медицинская страховка", "sveikatos draudimas", "n"), Word("удостоверение личности", "asmens dokumentas", "n")
    )),
    "17" to Theme("17", "17. Лекарства и болезни", listOf(
        Word("лекарства", "vaistai", "n"), Word("рецепт", "receptas", "n"),
        Word("обезболивающие", "vaistai nuo skausmo (skausmas)", "n"), Word("от температуры", "nuo temperatūros", "other"),
        Word("от насморка", "nuo slogos", "other"), Word("от аллергии", "nuo alergijos", "other"),
        Word("от кашля", "nuo kosulio", "other"), Word("принимать лекарства", "gerti vaistus", "v"),
        Word("перед едой", "prieš valgį", "other"), Word("после еды", "po valgio", "other"),
        Word("принимать таблетку один / два / три раза в день", "gerti tabletę vieną kartą / du / tris kartus per dieną", "other"),
        Word("таблетка", "tabletė", "n"), Word("антибиотики", "antibiotikai", "n"),
        Word("сироп от кашля", "sirupas nuo kosulio", "n"), Word("спрей", "purškalas", "n"),
        Word("спрей для горла / носа", "gerklės / nosies purškalas", "n"), Word("капли", "lašai", "n"),
        Word("капли для глаз / ушей / сердца", "akių / ausų / širdies lašai", "n"), Word("кровь", "kraujas", "n"),
        Word("кровяное давление", "kraujospūdis, kraujospūdžio", "n"),
        Word("низкое, высокое, нормальное кровяное давление", "žemas, aukštas, normalus kraujospūdis", "adj"),
        Word("делать", "padaryti, padaro, padarė ką?", "v"), Word("сдавать анализы", "padaryti tyrimus", "v"),
        Word("анализ крови", "kraujo tyrimas", "n"), Word("анализ мочи", "šlapimo tyrimas", "n"),
        Word("скорая помощь", "greitoji (pagalba)", "n"), Word("вызывать", "iškviesti, iškviečia, iškvietė ką?", "v"),
        Word("вызывать врача / скорую", "iškviesti gydytoją, greitąją (pagalbą)", "v"), Word("кашлять", "kosėti, kosėja, kosėjo", "v"),
        Word("тошнить", "pykinti, pykina, pykino ką?", "v"), Word("рвать", "vemti, vemia, vėmė", "v"),
        Word("поносить (диарея)", "viduriuoti, viduriuoja, viduriavo", "v"), Word("болезнь", "liga", "n"),
        Word("аллергия", "alergija", "n"), Word("аллергический / аллергическая", "alergiškas, alergiška", "adj"),
        Word("грипп", "gripas", "n"), Word("насморк", "sloga", "n"),
        Word("кашель", "kosulys", "n"), Word("бронхит", "bronchitas", "n"),
        Word("воспаление лёгких", "plaučių uždegimas", "n"), Word("ангина", "angina", "n"),
        Word("прививаться", "pasiskiepyti, pasiskiepija, pasiskiepijo nuo ko?", "v")
    )),
    "18" to Theme("18", "18. Работа и профессии", listOf(
        Word("работа", "darbas", "n"), Word("выходной / день отдыха", "poilsio / nedarbo diena", "n"),
        Word("рабочее место", "darbovietė", "n"), Word("предприятие, компания", "įmonė", "n"),
        Word("директор, руководитель", "direktorius, direktorė", "n"), Word("коллега", "kolega, kolegė", "n"),
        Word("сотрудник / сотрудница", "darbuotojas, darbuotoja", "n"), Word("клиент / клиентка", "klientas, klientė", "n"),
        Word("занятый / занятая", "užsiėmęs, užsiėmusi", "adj"), Word("командировка", "komandiruotė", "n"),
        Word("собрание", "susirinkimas", "n"), Word("встреча", "susitikimas", "n"),
        Word("кабинет", "kabinetas", "n"), Word("начинаться", "prasidėti, prasideda, prasidėjo", "v"),
        Word("заканчиваться", "pasibaigti, pasibaigia, pasibaigė", "v"), Word("начинать", "pradėti, pradeda, pradėjo ką?", "v"),
        Word("заканчивать", "baigti, baigia, baigė ką?", "v"), Word("заканчивать работу", "baigti darbą", "v"),
        Word("обеденный перерыв", "pietų pertrauka", "n"), Word("быть в отпуске, отдыхать", "atostogauti, atostogauja, atostogavo", "v"),
        Word("отпуск", "atostogos", "n"), Word("распечатать", "išspausdinti, išspausdina, išspausdino ką?", "v"),
        Word("документ", "dokumentas", "n"), Word("копия", "kopija", "n"),
        Word("делать копии", "daryti, daro, darė kopijas", "v"), Word("передавать, сообщать", "perduoti, perduoda, perdavė ką? kam?", "v"),
        Word("давать, вручать", "paduoti, paduoda, padavė ką? kam?", "v"), Word("говорить, сказать", "pasakyti, pasako, pasakė ką? kam?", "v"),
        Word("относить", "nunešti, nuneša, nunešė ką? kam?", "v"), Word("писать", "rašyti, rašo, rašė ką? kam?", "v"),
        Word("отправлять", "išsiųsti, išsiunčia, išsiuntė ką? kam?", "v"), Word("получать", "gauti, gauna, gavo ką? kam?", "v"),
        Word("электронное письмо", "elektroninis laiškas", "n"), Word("подписывать", "pasirašyti, pasirašo, pasirašė ką?", "v"),
        Word("parašas", "parašas", "n"), Word("договор", "sutartis, sutarties", "n"),
        Word("подождать", "palaukti, palaukia, palaukė ko?", "v"), Word("спросить", "paklausti, paklausia, paklausė", "v"),
        Word("позвонить", "paskambinti, paskambina, paskambino kam?", "v"), Word("бумага", "popierius", "n"),
        Word("лист бумаги", "popieriaus lapas", "n"), Word("компьютер", "kompiuteris, kompiuterio", "n"),
        Word("принтер", "spausdintuvas", "n"), Word("профессии", "profesijos", "n"),
        Word("администратор", "administratorius, administratorė", "n"), Word("секретарь", "sekretorius, sekretorė", "n"),
        Word("учитель / учительница", "mokytojas, mokytoja", "n"), Word("преподаватель", "dėstytojas, dėstytoja", "n"),
        Word("врач", "gydytojas, gydytoja", "n"), Word("медсестра / медбрат", "slaugytojas, slaugytoja", "n"),
        Word("менеджер", "vadybininkas, vadybininkė", "n"), Word("бизнесмен / бизнесвумен", "verslininkas, verslininkė", "n"),
        Word("юрист", "teisininkas, teisininkė", "n"), Word("бухгалтер", "buhalteris, buhalterio ; buhalterė", "n"),
        Word("инженер", "inžinierius, inžinierė", "n"), Word("журналист", "žurnalistas, žurnalistė", "n"),
        Word("архитектор", "architektas, architektė", "n"), Word("IT-специалист", "IT (informacinių technologijų) specialistas, specialistė", "n"),
        Word("актёр / актриса", "aktorius, aktorė", "n"), Word("певец / певица", "dainininkas, dainininkė", "n"),
        Word("музыкант", "muzikantas, muzikantė", "n"), Word("водитель", "vairuotojas, vairuotoja", "n"),
        Word("строитель", "statybininkas, statybininkė", "n"), Word("парикмахер", "kirpėjas, kirpėja", "n"),
        Word("официант / официантка", "padavėjas, padavėja", "n"), Word("продавец / продавщица", "pardavėjas, pardavėja", "n"),
        Word("образование", "išsilavinimas", "n"), Word("высшее образование", "aukštasis", "n"),
        Word("профессиональное образование", "profesinis", "n"), Word("среднее образование (полное)", "vidurinis", "n"),
        Word("основное среднее образование", "pagrindinis", "n"), Word("начальное образование", "pradinis", "n"),
        Word("с", "nuo", "other"), Word("до", "iki", "other"),
        Word("перед, некоторое время назад", "prieš", "other"), Word("во время", "per", "other"),
        Word("о", "apie", "other"), Word("сразу, немедленно", "tuojau / tuoj", "adv")
    )),
    "19" to Theme("19", "19. Образование и учёба", listOf(
        Word("профессор", "profesorius, profesorė", "n"), Word("университет", "universitetas", "n"),
        Word("академия", "akademija", "n"), Word("колледж", "kolegija", "n"),
        Word("библиотека", "biblioteka", "n"), Word("аудитория", "auditorija", "n"),
        Word("курс (первый, второй, …)", "kursas (pirmas, antras, …)", "n"), Word("учиться", "mokytis, mokosi, mokėsi ko?", "v"),
        Word("учить", "mokyti, moko, mokė ką? ko?", "v"), Word("изучать", "studijuoti, studijuoja, studijavo ką?", "v"),
        Word("знать", "žinoti, žino, žinojo", "v"), Word("забывать", "pamiršti, pamiršta, pamiršo ką?", "v"),
        Word("повторять", "pakartoti, pakartoja, pakartojo", "v"), Word("слушать", "klausyti, klauso, klausė ko?", "v"),
        Word("расписание", "tvarkaraštis, tvarkaraščio", "n"), Word("страница", "puslapis, puslapio", "n"),
        Word("задание", "užduotis, užduoties", "n"), Word("упражнение", "pratimas", "n"),
        Word("вопрос", "klausimas", "n"), Word("текст", "tekstas", "n"),
        Word("домашняя работа", "namų darbas", "n"), Word("делать домашнюю работу", "daryti namų darbą", "v"),
        Word("лекция", "paskaita", "n"), Word("семинар", "seminaras", "n"),
        Word("экзамен", "egzaminas", "n"), Word("тест", "testas", "n"),
        Word("сдавать экзамен", "laikyti, laiko, laikė egzaminą", "v"), Word("сдавать экзамен (успешно)", "išlaikyti, išlaiko, išlaikė egzaminą", "v"),
        Word("оценка", "pažymys", "n"), Word("диплом", "diplomas", "n"),
        Word("сертификат", "pažymėjimas", "n"), Word("биология", "biologija", "n"),
        Word("химия", "chemija", "n"), Word("изобразительное искусство", "dailė", "n"),
        Word("филология (литовский, английский, французский, …)", "filologija (lietuvių, anglų, prancūzų, …)", "n"),
        Word("экономика", "ekonomika", "n"), Word("физика", "fizika", "n"),
        Word("география", "geografija", "n"), Word("информатика", "informatika", "n"),
        Word("история", "istorija", "n"), Word("язык (литовский, английский, французский, …)", "kalba (lietuvių, anglų, prancūzų, …)", "n"),
        Word("математика", "matematika", "n"), Word("медицина", "medicina", "n"),
        Word("политология", "politologija", "n"), Word("психология", "psichologija", "n"),
        Word("право", "teisė", "n"), Word("менеджмент", "vadyba", "n"),
        Word("журналистика", "žurnalistika", "n"), Word("книга", "knyga", "n"),
        Word("учебник", "vadovėlis, vadovėlio", "n"), Word("словарь", "žodynas", "n"),
        Word("ручка", "rašiklis, rašiklio", "n"), Word("карандаш", "pieštukas", "n"),
        Word("ластик", "trintukas", "n"), Word("тетрадь", "sąsiuvinis, sąsiuvinio", "n"),
        Word("одалживать", "paskolinti, paskolina, paskolino ką?", "v")
    )),
    "20" to Theme("20", "20. Времена года и досуг", listOf(
        Word("досуг", "laisvalaikis, laisvalaikio", "n"), Word("отдыхать", "pailsėti, pailsi, pailsėjo", "v"),
        Word("нравиться", "mėgti, mėgsta, mėgo", "v"), Word("делать", "veikti, veikia, veikė", "v"),
        Word("музыка", "muzika", "n"), Word("концерт", "koncertas", "n"),
        Word("опера", "opera", "n"), Word("балет", "baletas", "n"),
        Word("гитара", "gitara", "n"), Word("пианино", "pianinas", "n"),
        Word("фортепиано", "fortepijonas", "n"), Word("слушать", "klausyti, klauso, klausė ko?", "v"),
        Word("танцевать", "šokti, šoka, šoko", "v"), Word("петь", "dainuoti, dainuoja, dainavo", "v"),
        Word("играть (на инструменте)", "groti, groja, grojo", "v"), Word("уметь, знать (как делать)", "mokėti, moka, mokėjo", "v"),
        Word("выставка", "paroda", "n"), Word("фотография", "fotografija", "n"),
        Word("картина", "paveikslas", "n"), Word("скульптура", "skulptūra", "n"),
        Word("спорт", "sportas", "n"), Word("стадион", "stadionas", "n"),
        Word("бассейн", "baseinas", "n"), Word("баскетбол", "krepšinis, krepšinio", "n"),
        Word("футбол", "futbolas", "n"), Word("теннис", "tenisas", "n"),
        Word("играть", "žaisti, žaidžia, žaidė ką?, kuo?", "v"), Word("шашки", "šaškės", "n"),
        Word("шахматы", "šachmatai", "n"), Word("играть в баскетбол", "žaisti krepšinį", "v"),
        Word("играть в шашки", "žaisti šaškėmis", "v"), Word("заниматься спортом", "sportuoti, sportuoja, sportavo", "v"),
        Word("плавать", "plaukioti, plaukioja, plaukiojo", "v"), Word("ходить гулять", "eiti pasivaikščioti", "v"),
        Word("бегать трусцой", "bėgioti, bėgioja, bėgiojo", "v"), Word("кататься на лыжах", "slidinėti, slidinėja, slidinėjo", "v"),
        Word("ездить", "važinėti, važinėja, važinėjo", "v"), Word("театр", "teatras", "n"),
        Word("спектакль", "spektaklis, spektaklio", "n"), Word("кино", "kinas", "n"),
        Word("фильм", "filmas", "n"), Word("зал", "salė", "n"),
        Word("ряд", "eilė", "n"), Word("место", "vieta", "n"),
        Word("смотреть", "žiūrėti, žiūri, žiūrėjo ką?", "v"), Word("смотреть телевизор", "žiūrėti televizorių", "v"),
        Word("путешествие", "kelionė", "n"), Word("самолёт", "lėktuvas", "n"),
        Word("багаж", "bagažas", "n"), Word("путешествовать", "keliauti, keliauja, keliavo", "v"),
        Word("лететь", "skristi, skrenda, skrido", "v"), Word("возвращаться", "grįžti, grįžta, grįžo", "v"),
        Word("море", "jūra", "n"), Word("озеро", "ežeras", "n"),
        Word("река", "upė", "n"), Word("лес", "miškas", "n"),
        Word("горы", "kalnai", "n"), Word("деревня", "kaimas", "n"),
        Word("дача", "sodyba", "n"), Word("собирать грибы", "grybauti, grybauja, grybavo", "v"),
        Word("рыбачить", "žvejoti, žvejoja, žvejojo", "v"), Word("лето", "vasara", "n"),
        Word("осень", "ruduo, rudens", "n"), Word("зима", "žiema", "n"),
        Word("весна", "pavasaris, pavasario", "n"), Word("очень", "labai", "adv"),
        Word("больше", "labiau", "adv")
    )),
    "21" to Theme("21", "21. Праздники", listOf(
        Word("праздник", "šventė", "n"), Word("праздновать", "švęsti, švenčia, šventė ką?", "v"),
        Word("день рождения", "gimtadienis, gimtadienio", "n"), Word("день именин", "vardadienis, vardadienio", "n"),
        Word("юбилей", "jubiliejus", "n"), Word("приглашать", "kviesti, kviečia, kvietė ką?", "v"),
        Word("вечеринка", "vakarėlis, vakarėlio", "n"), Word("гость", "svečias", "n"),
        Word("ходить в гости", "eiti į svečius", "v"), Word("приглашать в гости", "kviesti į svečius", "v"),
        Word("быть в гостях", "būti svečiuose", "v"), Word("дарить", "dovanoti, dovanoja, dovanojo ką?, ko?", "v"),
        Word("получать", "gauti, gauna, gavo ką?, ko?", "v"), Word("подарок", "dovana", "n"),
        Word("цветок", "gėlė", "n"), Word("открытка", "atvirukas", "n"),
        Word("написать открытку", "užrašyti, užrašo, užrašė atviruką", "v"), Word("отправить открытку", "išsiųsti, išsiunčia, išsiuntė atviruką", "v"),
        Word("торт", "tortas", "n"), Word("свечка", "žvakutė", "n"),
        Word("Сочельник", "Kūčios", "n"), Word("рождественские печенья", "kūčiukai", "n"),
        Word("гимн", "himnas", "n"), Word("петь гимн", "giedoti, gieda, giedojo himną", "v"),
        Word("поздравлять", "sveikinti, sveikina, sveikino ką?", "v"), Word("желать", "linkėti, linki, linkėjo ko?", "v"),
        Word("Рождество", "Kalėdos", "n"), Word("ёлка", "eglė / eglutė", "n"),
        Word("Дед Мороз (Санта Клаус)", "Kalėdų senelis", "n"), Word("свеча", "žvakė", "n"),
        Word("Новый год", "Naujieji metai", "n"), Word("встречать Новый год", "sutikti, sutinka, sutiko Naujuosius metus", "v"),
        Word("фейерверки", "fejerverkai", "n"), Word("Пасха", "Velykos", "n"),
        Word("пасхальное яйцо", "margutis, margučio", "n"), Word("красить яйца", "dažyti, dažo, dažė kiaušinius", "v"),
        Word("катать яйца", "ridenti, ridena, rideno margučius", "v"), Word("государственные праздники", "valstybinės šventės", "n"),
        Word("День восстановления государственности Литвы (16 февраля)", "Vasario šešiolikta (02-16) Lietuvos valstybės atkūrimo diena", "n"),
        Word("День восстановления независимости Литвы (11 марта)", "Kovo vienuolikta (03-11) Lietuvos nepriklausomybės atkūrimo diena", "n"),
        Word("День государственности (6 июля)", "Liepos šešta (07-06) Lietuvos valstybės diena", "n"),
        Word("президент", "prezidentas, prezidentė", "n"), Word("флаг", "vėliava", "n"),
        Word("успех", "sėkmė", "n"), Word("любовь", "meilė", "n"),
        Word("счастье", "laimė", "n"), Word("радость", "džiaugsmas", "n"),
        Word("счастливый / счастливая", "laimingas, laiminga", "adj"),
        Word("любимый / любимая", "mylimas, mylima", "adj"), Word("уважаемый / уважаемая", "gerbiamas, gerbiama", "adj"),
        Word("красочный / красочная", "spalvingas, spalvinga", "adj"), Word("популярный / популярная", "populiarus, populiari", "adj")
    ))
)

val GLOBAL_POOL = THEMES_DATA.values.flatMap { it.words }
